import type { ApiProduct } from "./api/types";

export const LOCAL_PRODUCTS: ApiProduct[] = [
  {
    id: "local-1",
    title: "Áo Len Thủ Công",
    description: "Áo len được đan tay tỉ mỉ, chất liệu len mềm mại, giữ ấm tốt.",
    price: 450000,
    images: ["/products/shirts/ao-len-1.webp", "/products/shirts/ao-len-2.webp"],
    category: "shirt",
    size: "M",
    condition: "new",
    ownerId: "system",
    status: "available",
    views: 120,
    isKnitwear: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "local-2",
    title: "Chân Váy Aufra",
    description: "Chân váy Aufra phong cách vintage, nhẹ nhàng và nữ tính.",
    price: 320000,
    images: ["/products/skirts/aufra-1.webp", "/products/skirts/aufra-2.webp"],
    category: "others",
    size: "S",
    condition: "like_new",
    ownerId: "system",
    status: "available",
    views: 85,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "local-3",
    title: "Quần Jeans Đậm S",
    description: "Quần jeans xanh đậm, form dáng chuẩn, dễ phối đồ.",
    price: 380000,
    images: ["/products/pants/jeans-đam-s1.webp", "/products/pants/jeans-đam-s2.webp"],
    category: "pants",
    size: "S",
    condition: "good",
    ownerId: "system",
    status: "available",
    views: 64,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "local-4",
    title: "Quần Jeans Wash Rộng",
    description: "Quần jeans ống rộng, wash màu cá tính, phong cách streetwear.",
    price: 420000,
    images: ["/products/pants/jeans-wash-rong1.webp"],
    category: "pants",
    size: "L",
    condition: "new",
    ownerId: "system",
    status: "available",
    views: 92,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "local-5",
    title: "Quần Godmother",
    description: "Quần vải cao cấp phong cách Godmother, sang trọng và thanh lịch.",
    price: 550000,
    images: ["/products/pants/godmother1.webp", "/products/pants/godmother2.webp"],
    category: "pants",
    size: "M",
    condition: "like_new",
    ownerId: "system",
    status: "available",
    views: 45,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "local-6",
    title: "Quần Whose Pants",
    description: "Quần phong cách Whose, độc đáo và phá cách.",
    price: 480000,
    images: ["/products/pants/whose-1.webp", "/products/pants/whose-2.webp"],
    category: "pants",
    size: "M",
    condition: "new",
    ownerId: "system",
    status: "available",
    views: 38,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "local-7",
    title: "Áo Khoác Kẻ Sọc",
    description: "Áo khoác họa tiết kẻ sọc thời thượng, phù hợp cho mùa thu đông.",
    price: 620000,
    images: ["/products/jackets/jacket-kesoc1.webp", "/products/jackets/jacket-kesoc2.webp"],
    category: "jacket",
    size: "L",
    condition: "good",
    ownerId: "system",
    status: "available",
    views: 77,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "local-8",
    title: "Áo Cardigan Đỏ",
    description: "Áo cardigan màu đỏ nổi bật, chất liệu len dày dặn.",
    price: 490000,
    images: ["/products/jackets/cadigant-red-1.webp"],
    category: "jacket",
    size: "M",
    condition: "new",
    ownerId: "system",
    status: "available",
    views: 110,
    isKnitwear: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "local-10",
    title: "Váy Len Vintage",
    description: "Váy len phong cách vintage, chất liệu mềm mại, tôn dáng.",
    price: 390000,
    images: ["/products/skirts/aufra-1.webp"],
    category: "others",
    size: "S",
    condition: "new",
    ownerId: "system",
    status: "available",
    isKnitwear: true,
    views: 42,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "local-11",
    title: "Áo Khoác Len Họa Tiết",
    description: "Áo khoác len với họa tiết kẻ sọc độc đáo, phong cách thanh lịch.",
    price: 580000,
    images: ["/products/jackets/jacket-kesoc1.webp"],
    category: "jacket",
    size: "L",
    condition: "like_new",
    ownerId: "system",
    status: "available",
    isKnitwear: true,
    views: 56,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "local-12",
    title: "Khăn Len Pastel",
    description: "Khăn len màu sắc pastel nhẹ nhàng, giữ ấm hoàn hảo.",
    price: 180000,
    images: ["/products/accessories/umbrela1.webp"],
    category: "others",
    size: "FREESIZE",
    condition: "new",
    ownerId: "system",
    status: "available",
    isKnitwear: true,
    views: 29,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "local-13",
    title: "Quần Len Suông",
    description: "Quần len ống suông thoải mái, phù hợp mặc ở nhà hoặc dạo phố.",
    price: 350000,
    images: ["/products/pants/jeans-wash-rong1.webp"],
    category: "pants",
    size: "M",
    condition: "new",
    ownerId: "system",
    status: "available",
    isKnitwear: true,
    views: 88,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "local-14",
    title: "Áo Len Cổ Lọ",
    description: "Áo len cổ lọ giữ ấm tuyệt đối, form dáng hiện đại.",
    price: 420000,
    images: ["/products/jackets/jacket-kesoc2.webp"],
    category: "jacket",
    size: "M",
    condition: "new",
    ownerId: "system",
    status: "available",
    isKnitwear: true,
    views: 145,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "local-9",
    title: "Ô (Dù) Che Nắng",
    description: "Phụ kiện ô che nắng họa tiết xinh xắn.",
    price: 150000,
    images: ["/products/accessories/umbrela1.webp"],
    category: "others",
    size: "FREESIZE",
    condition: "new",
    ownerId: "system",
    status: "available",
    views: 25,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
