import type { ApiProduct } from "./api/types";

export const LOCAL_PRODUCTS: ApiProduct[] = [
  {
    id: "local-1",
    title: "Áo Len Thủ Công",
    description: "Áo len được đan tay tỉ mỉ, chất liệu len mềm mại, giữ ấm tốt.",
    price: 450000,
    images: ["/products/knitwear/ao-len-1.webp", "/products/knitwear/ao-len-2.webp"],
    category: "knitwear",
    size: "M",
    condition: "new",
    ownerId: "system",
    status: "available",
    views: 120,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "local-8",
    title: "Áo Cardigan Đỏ",
    description: "Áo cardigan màu đỏ nổi bật, chất liệu len dày dặn.",
    price: 490000,
    images: ["/products/knitwear/cadigant-red-1.webp"],
    category: "knitwear",
    size: "M",
    condition: "new",
    ownerId: "system",
    status: "available",
    views: 110,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  {
    id: "local-knit-2",
    title: "Bookmark Ếch Xanh",
    description: "Bookmark len hình chú ếch xanh đáng yêu, quà tặng ý nghĩa cho người yêu sách.",
    price: 45000,
    images: ["/products/knitwear/book-mark-ech.jpg"],
    category: "others",
    size: "FREE",
    condition: "new",
    ownerId: "system",
    status: "available",
    views: 89,
    isKnitwear: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "local-knit-3",
    title: "Móc Khóa Cá Heo",
    description: "Móc khóa len hình cá heo nhỏ xinh, màu sắc tươi tắn.",
    price: 35000,
    images: ["/products/knitwear/ca-heo.jpg"],
    category: "others",
    size: "FREE",
    condition: "new",
    ownerId: "system",
    status: "available",
    views: 42,
    isKnitwear: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "local-knit-4",
    title: "Móc Khóa Xương Cá",
    description: "Phụ kiện móc khóa xương cá độc đáo, làm từ len cotton an toàn.",
    price: 30000,
    images: [
      "/products/knitwear/xuong-ca.jpg",
      "/products/knitwear/xuong-ca-1.jpg",
      "/products/knitwear/xuong-ca-2.jpg"
    ],
    category: "others",
    size: "FREE",
    condition: "new",
    ownerId: "system",
    status: "available",
    views: 67,
    isKnitwear: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "local-knit-5",
    title: "Nàng Tiên Cá Vô Tri",
    description: "Búp bê len nàng tiên cá với biểu cảm vô tri vô cùng hài hước.",
    price: 85000,
    images: ["/products/knitwear/tiencavotri.jpg"],
    category: "others",
    size: "FREE",
    condition: "new",
    ownerId: "system",
    status: "available",
    views: 112,
    isKnitwear: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "local-knit-6",
    title: "Móc Khóa Ếch Trầm Cảm",
    description: "Móc khóa len hình chú ếch biểu cảm hài hước, độc lạ.",
    price: 35000,
    images: ["/products/knitwear/moc-khoa-ech.jpg"],
    category: "others",
    size: "FREE",
    condition: "new",
    ownerId: "system",
    status: "available",
    views: 95,
    isKnitwear: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "local-2",
    title: "Chân Váy Aufra",
    description: "Chân váy Aufra phong cách vintage, nhẹ nhàng và nữ tính.",
    price: 320000,
    images: ["/products/skirts/aufra-1.webp", "/products/skirts/aufra-2.webp"],
    category: "others",
    size: "S",
    condition: "like_new",
    ownerId: "system",
    status: "available",
    views: 85,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "local-3",
    title: "Quần Jeans Đậm S",
    description: "Quần jeans xanh đậm, form dáng chuẩn, dễ phối đồ.",
    price: 380000,
    images: ["/products/pants/jeans-đam-s1.webp", "/products/pants/jeans-đam-s2.webp"],
    category: "pants",
    size: "S",
    condition: "good",
    ownerId: "system",
    status: "available",
    views: 64,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "local-4",
    title: "Quần Jeans Wash Rộng",
    description: "Quần jeans ống rộng, wash màu cá tính, phong cách streetwear.",
    price: 420000,
    images: ["/products/pants/jeans-wash-rong1.webp"],
    category: "pants",
    size: "L",
    condition: "new",
    ownerId: "system",
    status: "available",
    views: 92,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "local-5",
    title: "Quần Godmother",
    description: "Quần vải cao cấp phong cách Godmother, sang trọng và thanh lịch.",
    price: 550000,
    images: ["/products/pants/godmother1.webp", "/products/pants/godmother2.webp"],
    category: "pants",
    size: "M",
    condition: "like_new",
    ownerId: "system",
    status: "available",
    views: 45,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "local-6",
    title: "Quần Whose Pants",
    description: "Quần phong cách Whose, độc đáo và phá cách.",
    price: 480000,
    images: ["/products/pants/whose-1.webp", "/products/pants/whose-2.webp"],
    category: "pants",
    size: "M",
    condition: "new",
    ownerId: "system",
    status: "available",
    views: 38,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "local-7",
    title: "Áo Khoác Kẻ Sọc",
    description: "Áo khoác họa tiết kẻ sọc thời thượng, phù hợp cho mùa thu đông.",
    price: 620000,
    images: ["/products/jackets/jacket-kesoc1.webp", "/products/jackets/jacket-kesoc2.webp"],
    category: "jacket",
    size: "L",
    condition: "good",
    ownerId: "system",
    status: "available",
    views: 77,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "local-9",
    title: "Ô (Dù) Che Nắng",
    description: "Phụ kiện ô che nắng họa tiết xinh xắn.",
    price: 150000,
    images: ["/products/accessories/umbrela1.webp"],
    category: "others",
    size: "FREESIZE",
    condition: "new",
    ownerId: "system",
    status: "available",
    views: 25,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
